# -*- coding: utf-8 -*-
"""Copia_de_coder_jorge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Jorge-guzzo/coderhouse/blob/main/Copia_de_coder_jorge.ipynb

# Nueva sección
"""

pip install requests

import requests
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects

import json
import pandas as pd
import time

import os
from configparser import ConfigParser

from pathlib import Path

config = ConfigParser()

url = 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
endpoint = {
"data": [
{
"cover": "https://academy-public.coinmarketcap.com/optimized-uploads/0aec0502868046419ceace229f92601f.gif",
"assets": [
{
"id": 1027,
"name": "Ethereum",
"symbol": "ETH",
"slug": "ethereum"
}
],
"created_at": "2021-05-05T00:00:00Z",
"released_at": "2021-05-05T00:00:00Z",
"title": "Article Title",
"subtitle": "Article Subtitle",
"type": "alexandria",
"source_name": "Connor Sephton",
"source_url": "https://coinmarketcap.com/alexandria/article/coinmarketcap-news-august-9-u-s-comes-for-tornado-cash"
}
],
"status": {
"timestamp": "2018-06-02T22:51:28.209Z",
"error_code": 0,
"error_message": "",
"elapsed": 10,
"credit_count": 1
}}
CMC_PRO_API_KEY = '51cf7543-d1ab-4b87-be0c-171773c1db67'
params = {
  'start':'1',
  'limit':'50',
  'convert':'ARS'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': 'b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c',
}

session = Session()
session.headers.update(headers)

resp = requests.get(url,params=params,headers=headers)

print(CMC_PRO_API_KEY)

data = resp.json()

if resp.status_code == 200:
  resp_json = resp.json()
else:
    print("Error al hacer la solicitud:", resp.status_code)

print(resp.json)

resp.json()["data"]

print(resp_json)
print(resp_json.keys())

stations_data = resp_json["data"]
df_stations_new = pd.DataFrame(stations_data)
df_stations_new.head(10)

